apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  type: LoadBalancer
  ports:
    - name: "7050"
      port: 7050
      targetPort: 7050
  selector:
    io.kompose.service: backend
