apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chapter14-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: mustafakeser/backend:latest
          name: backend
          ports:
            - containerPort: 7050
              hostPort: 7050
              protocol: TCP
      restartPolicy: Always
