apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: logging
  name: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logging
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chapter14-default: "true"
        io.kompose.service: logging
    spec:
      containers:
        - env:
            - name: GF_INSTALL_PLUGINS
              value: grafana-piechart-panel
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "123456"
            - name: GF_SECURITY_ADMIN_USER
              value: admin
          image: grafana/grafana
          name: logging
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
      restartPolicy: Always
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
