apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chapter14-default: "true"
        io.kompose.service: webapp
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres:123456@postgres:5432/postgres
          image: mustafakeser/webapp:latest
          name: webapp
          ports:
            - containerPort: 2000
              hostPort: 2000
              protocol: TCP
      restartPolicy: Always
