{
 "title": "example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "last 15 connections ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, \"time\", device FROM connections ORDER BY \"time\" DESC LIMIT 15 "
    }
   ]
  },
  {
   "title": "webapp_http_requests_created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "webapp_http_requests_created", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "prometheus_sd_http_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "prometheus_sd_http_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "webapp_http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "webapp_http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}